### ISSUE TITLE
clamscan library

### ISSUE THREAD

**Issue by Mgpuentes** [truework/lambda-s3-antivirus#1]
I have my lambda function up and running. The cvd files have no problem downloading from the s3 bucket. I run into a problem during the clamscan (SCAN FAILED). The error I get is `Error: Command failed: ./clamscan -v -a --stdout -d /tmp/ '/tmp/download/virus-test.rtf'
./clamscan: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory`

where virus-test.rtf is my test file

**Comment by Mgpuentes** [comment]
I solved this issue by downloading the libraries required separately and including them in the lambda.zip

**Comment by victorkabdebon** [comment]
Hey Matthew, 

Apologies I didn't see your comment, somebody else made a pull request to fix the issue you faced. Hopefully that'll help you!
