### ISSUE TITLE
`/clamscan: error while loading shared libraries: libclamav.so.9: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by jobetdelima** [truework/lambda-s3-antivirus#11]
Hi,

I've ran the commands below individually on my Mac...
```
mkdir -p clamav

echo "-- Downloading AmazonLinux container --"
docker pull amazonlinux
docker create -i -t -v ${PWD}/clamav:/home/docker  --name s3-antivirus-builder amazonlinux
docker start s3-antivirus-builder

echo "-- Updating, downloading and unpacking clamAV and ClamAV update --"
docker exec -it -w /home/docker s3-antivirus-builder yum install -y cpio yum-utils
docker exec -it -w /home/docker s3-antivirus-builder yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
docker exec -it -w /home/docker s3-antivirus-builder yum-config-manager --enable epel
docker exec -it -w /home/docker s3-antivirus-builder yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update json-c pcre2
docker exec -it -w /home/docker s3-antivirus-builder /bin/sh -c "echo 'folder content' && ls -la"
docker exec -it -w /home/docker s3-antivirus-builder /bin/sh -c "rpm2cpio clamav-0*.rpm | cpio -idmv"
docker exec -it -w /home/docker s3-antivirus-builder /bin/sh -c "rpm2cpio clamav-lib*.rpm | cpio -idmv"
docker exec -it -w /home/docker s3-antivirus-builder /bin/sh -c "rpm2cpio clamav-update*.rpm | cpio -idmv"
docker exec -it -w /home/docker s3-antivirus-builder /bin/sh -c "rpm2cpio json-c*.rpm | cpio -idmv"
docker exec -it -w /home/docker s3-antivirus-builder /bin/sh -c "rpm2cpio pcre2*.rpm | cpio -idmv"
```
At this point, things seem to be all well.

I then hopped onto a shell on the container, went to the `home/docker/usr/bin` and tried to execute `clamscan`.

I got this error =>  `/clamscan: error while loading shared libraries: libclamav.so.9: cannot open shared object file: No such file or directory`

I was thinking maybe it just can't find where the libraries are, so I essentially replicated the next commands in the script, i.e.
```
mkdir ./bin

echo "-- Copying the executables and required libraries --"
cp clamav/usr/bin/clamscan clamav/usr/bin/freshclam clamav/usr/lib64/* bin/.
```

except instead of copying those files over to my machine's local `bin/` folder, I did it on another folder inside the container, i.e. `home/docker/test`

I then executed clamscan  from inside that folder thinking it should now be able to find all the dependencies it needs --- I mean, the contents of the local `bin/` folder is what gets included in the lambda zip after all.

Anyways, no joy as I still ended up with the same error. That is `/clamscan: error while loading shared libraries: libclamav.so.9: cannot open shared object file: No such file or directory`

I'm thinking this would be a problem that would also surface when the lambda runs on AWS. I saw at least one post referring to the issue. Albeit, without a solution.
 
Was there a step I've missed?

'Appreciate any help! Thanks!

**Comment by JaieParker** [comment]
Heya I found this fix: https://github.com/upsidetravel/bucket-antivirus-function/pull/126/files from the python code repo

**Comment by evangow** [comment]
For anyone else that comes to this thread, I recommend using Yumda, which makes it incredibly easy to create a zip file for clamav and deploy it to Lambda. The thread at the link below is helpful

https://github.com/lambci/yumda/issues/3

**Comment by zeusongit** [comment]
Did any of the solution solve your problem? I am having the same issue.

**Comment by tengfone** [comment]
Facing the same issue here even after applying the fix from @JaieParker . Only applies when I am running it locally on my local docker. Any solutions so far? @zeusongit

**Comment by Gueban** [comment]
applying the fix works for me :thinking: 

> Heya I found this fix: https://github.com/upsidetravel/bucket-antivirus-function/pull/126/files from the python code repo

thanks btw @JaieParker

**Comment by autocracy** [comment]
Corrected in latest refactor
