### ISSUE TITLE
ClamAV v102 support on Node 12

### ISSUE THREAD

**Issue by sethsacher** [truework/lambda-s3-antivirus#13]
I noticed a few issues related to missing dependencies trying to run ClamAV v102 on Node12. I followed a different pattern of pulling in those dependencies which should translate to this repo as well:

https://github.com/kindlyops/lambda-clamav-layer/pull/4

Question to the group - it's taking about 30 seconds to run clamscan against a single file using this pattern. Is that what you have observed as well? It's a bit longer than I was expecting.

**Comment by autocracy** [comment]
Obsoleted by using the static RPM image in our latest rework
