### ISSUE TITLE
Cloudflare prevents database update

### ISSUE THREAD

**Issue by bart** [truework/lambda-s3-antivirus#16]
Unfortunately it seems to be impossible anymore to download clamav anti-virus definition files via wget or curl. Cloudflare rules prevent that kind of direct access.

**Comment by autocracy** [comment]
Noticed this in the latest update and retested again with the commit from:

Tested again with this line: https://github.com/truework/lambda-s3-antivirus/commit/18b9ff2dc8f9308ee9fcdb52f1c6ddae621780db#diff-98d84580e888792099dcab7eb758d0cd76619c152e7cca2200b0a84fc3cd0d63R17

So I still see Cloudflare blocking wget & curl with default user agents but modifying that solves it. The lambda is still updating our definition files as of today. Going to close unless you have further info / evidence that as setup this script isn't working. Please also note that we update the definition files by calling `download-definitions.lambdaHandleEvent`, not by using curl / wget.
