### ISSUE TITLE
Incomplete requirements for clamscan to run

### ISSUE THREAD

**Issue by jlediet** [truework/lambda-s3-antivirus#2]
@victorkabdebon 

First this code has been **super helpful** in me being able to get S3 virus scanning working for my particular needs.

That being said I found that json-c and pcre2 were missing from the lambda.zip which were required for clamscan and freshclam to run.

I also found since you created your blog entry the requirements have changed for the s3 event trigger.   In that they should be set up on the lambda function itself and not through an s3 event.

I have a branch with the required changes included in them, but I didn't want to create an unsolicited pull request unless you were interested.

**Comment by victorkabdebon** [comment]
@jlediet,it seems like somebody else opened a similar issue but closed the issue, without doing a PR.

We welcome any PR as long as they are helpful, so feel free to open a PR, I'll merge it.

**Comment by jlediet** [comment]
@victorkabdebon I created PR for your review https://github.com/truework/lambda-s3-antivirus/pull/3

**Comment by victorkabdebon** [comment]
@jlediet awesome, @ewinchell07 merged it and I added you to the contributors, thanks again!
