### ISSUE TITLE
WARNING: Local version: 0.100.2 Recommended version: 0.101.0

### ISSUE THREAD

**Issue by awadodeh** [truework/lambda-s3-antivirus#6]
```
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.2 Recommended version: 0.101.0
```

This can be fixed by making sure that the ClamAv version is updated, just add this to line 19 to  build_lambda.sh:
`docker exec -it -w /home/docker s3-antivirus-builder yum update clamav
`

**Comment by autocracy** [comment]
Obsoleted by latest refactor
